repos:
  - repo: https://github.com/ambv/black
    rev: 24.3.0
    hooks:
      - id: black
        target_version: python3.8
  - repo: https://github.com/pycqa/flake8.git
    rev: "7.0.0"
    hooks:
      - id: flake8
  - repo: https://github.com/timothycrosley/isort
    rev: "5.13.2"
    hooks:
      - id: isort
