version: 2
workflows:
  version: 2
  test:
    jobs:
      - test-3.6
      - test-latest
      - test-2.7
jobs:
  test-3.6: &test-template
    docker:
      - image: circleci/python:3.6
        environment:
          PIPENV_VENV_IN_PROJECT: true
    working_directory: ~/repo
    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          key: deps9-{{ .Branch }}-{{ checksum "Pipfile.lock" }}
      - run:
          name: install dependencies
          command: |
            pipenv sync --dev
      - save_cache:
          key: deps9-{{ .Branch }}-{{ checksum "Pipfile.lock" }}
          paths:
            - ".venv"
      - run:
          name: run tests
          command: |
            pipenv run python tests/test.py
      - store_artifacts:
          path: test-reports
          destination: test-reports
  test-latest:
      <<: *test-template
      docker:
        - image: circleci/python:latest
  test-2.7:
      <<: *test-template
      docker:
        - image: circleci/python:2.7
