version: 2
workflows:
  version: 2
  test:
    jobs:
      - test-3.6
      - test-latest
jobs:
  test-3.6: &test-template
    docker:
      - image: circleci/python:3.6
        environment:
          PIPENV_VENV_IN_PROJECT: true
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: install dependencies
          command: |
            pipenv sync --dev
      - run:
          name: run tests
          command: |
            pipenv run python tests/test.py
      - store_artifacts:
          path: test-reports
          destination: test-reports
  test-latest:
      <<: *test-template
      docker:
        - image: circleci/python:latest
