name: Send Release to PyPi
on:
  push:
    tags:
      - "*"
jobs:
  pypi:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - uses: dryan/action-polynotify@v1
        with:
          slack_webhook_url: ${{ secrets.SLACK_WEBHOOK_URL }}
          message: Publishing d3ploy to PyPi
      - uses: actions/checkout@v2
      - name: Setup Python 3.6
        uses: actions/setup-python@v1
        with:
          python-version: 3.6
      - name: Install poetry
        run: |
          curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python
          sudo ln -s $HOME/.poetry/bin/poetry /usr/local/bin/poetry
          poetry config virtualenvs.path ~/.poetry/environments
      - name: Run Python Unit Tests
        run: |
          poetry build
          poetry publish -u $PYPI_USERNAME -p $PYPI_PASSWORD
        env:
          PYPI_USERNAME: ${{ secrets.PYPI_USERNAME }}
          PYPI_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
      - uses: dryan/action-polynotify@v1
        with:
          slack_webhook_url: ${{ secrets.SLACK_WEBHOOK_URL }}
          message: Publishing d3ploy to PyPi succeeded
        if: success()
      - uses: dryan/action-polynotify@v1
        with:
          slack_webhook_url: ${{ secrets.SLACK_WEBHOOK_URL }}
          message: Publishing d3ploy to PyPi failed
        if: failure()
