name: Send Release to PyPi
on:
  push:
    tags:
      - "*"
jobs:
  pypi:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python 3.13
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"
      - name: Install uv
        uses: astral-sh/setup-uv@v3
      - name: Build & Publish
        run: |
          uv build
          uv publish
        env:
          PYPI_TOKEN: ${{ secrets.PYPI_TOKEN }}
